### ISSUE TITLE
Editable pdf issue

### ISSUE THREAD

**Issue by ulissesss** [i96751414/plugin.image.pdfreader#2]
Hello,
Regarding this limitation: 

> Currently PDF Reader can only read pdf files made of pictures, since its operation method's consists of extracting pictures from PDF files.

I was thinking maybe is a good idea to flatten the pdf before to read it. I found this python library:
https://pypi.org/project/fillpdf/
In this way this library will turn the pdf to a non-editable pdf and the plugin will read correctly the full page as an image.

**Comment by i96751414** [comment]
Hi,

I am afraid this won't be possible as this requires external libraries which are not part of Kodi's set of libraries.
The main problem is not the fact the libraries are not part of Kodi (as one could simply create a module for them) but the fact they are not pure-python libraries and use external binaries (which need to be compiled for each platform).
